wallpaper {
    monitor =  HDMI-A-1
    path = /home/junk/.config/hypr/wallpapers/red-sun-wallpaper.png
}

wallpaper {
    monitor =  DP-1
    path = /home/junk/.config/hypr/wallpapers/red-sun-wallpaper.png
}
