wallpaper {
    monitor =  HDMI-A-1
    path = /home/junk/.config/hypr/wallpapers/bnw-mountains.jpg
}

wallpaper {
    monitor =  DP-1
    path = /home/junk/.config/hypr/wallpapers/bnw-mountains.jpg
}
